### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by proycon** [CentreForDigitalHumanities/tscan#70]
The latest tscan release (0.9.8) is from Dec 2020, which was just a minor update. The last more functional release before that was by @mhkuu in 0.9.7 in Feb 2020. 

Would it be possible to do a new release? This is also relevant because the [CLARIAH Tool Discovery portal](https://tools.clariah.nl) harvests the latest release (based on git tag) only. Because it falls back to the old release, the harvested metadata does not reflect the current situation and changes in maintainership after the repository moved to you guys entirely.

Some sub-issues that may be relevant for release:

* [ ] Don't forget to update the codemeta.json so it reflects the actual release (I see you already did that once, great!)
* [ ] It would be best to remove all LaMachine dependencies/references as that is now deprecated and no longer a recommended solution for deploying t-scan. CLARIAH now recommends containerisation as described in the [CLARIAH Software Requirements](https://github.com/CLARIAH/clariah-plus/blob/main/requirements/software-requirements.md). As you rely both on Alpino (which is hard to install/containerize) as well as CLAM, you can use the Dockerfile that I build for our Alpino webservice as a good starting point: https://github.com/proycon/alpino_clam_webservice/blob/master/Dockerfile
* [ ] There have been various releases of underlying dependencies (ticcutils, libfolia, frog, timbl, CLAM) since the last release. So you may want to check if this all works properly. For building Frog and underlying dependencies (considering LaMachine) is deprecated, you can look at this script: https://github.com/LanguageMachines/frog/blob/master/build-deps.sh (which you can invoke from a Dockerfile). 

One more question: the tscan webservice as hosted in Nijmegen will dissappear this week (we have a big migration), it too ran on the latest release (not including all the unreleased improvements you made since then), so that was probably suboptimal anyway. We did have some tscan users though, can I refer them to a place where you guys are hosting tscan in Utrecht now?

**Comment by oktaal** [comment]
Thank you! I'll look into it next week. No problem to refer them to me: it's hosted at https://tscan.hum.uu.nl and people can mail me for an account (no sign up page exists as of yet).

**Comment by proycon** [comment]
Thanks, I already redirected several people so you may experience a bit of an influx of users.

If you want something more manageable for authentication (or rather: you don't want to manage a user db yourself), you might want to consider hooking up tscan to [CLARIAH's authentication infrastructure](https://github.com/CLARIAH/clariah-plus/blob/main/interest-groups/devops/docs/authentication/authentication_clariah_nl.md) (OpenID Connect). People can then simply login with their institutional credentials. If I understood Antal correctly, the tscan project is now funded by CLARIAH as well so it'd be a good solution and in accordance with the software/infrastructure requirements we have for CLARIAH. It's also relatively easy to set up as CLAM is designed to work nicely with it. I can give some extra pointers if you need help with this.

The only caveat is that you may still need a fallback authentication mechanism/user-db for *automated* clients (that's how we have set things up in Nijmegen), CLAM supports that as well.
