### ISSUE TITLE
Update LiNT level thresholds

### ISSUE THREAD

**Issue by lukavdplas** [CentreForDigitalHumanities/tscan#77]
2b034049c01ee6bf4b15b541cb9fa0cf3935f16a has updated the coefficients of the LiNT formula to the latest version, but not the thresholds of the discrete difficulty levels. The new thresholds for each level should be:

1. 0-34
2. 34-46
3. 46-60
4. 60+

**Comment by oktaal** [comment]
Closed by 3b2a402
